server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: user-center-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://162.14.69.240:3306/partner_match_system?serverTimezone=UTC
    username: coderyc
    password: coderyc
  session:
    timeout: 86400
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER



mybatis-plus:
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

tencent:
  cos:
    app-id: 1318575555
    secret-id: AKIDzsZ2HNHyWwDIQXXL1azZzGVdXDk8NVQ8
    secret-key: eBkHwedeZJrGXkokU1LRRNDvjRCurgJk
    bucket-name: partner-files-1318575555
    region-id: ap-chengdu
    base-url: https://partner-files-1318575555.cos.ap-chengdu.myqcloud.com
